// generated by go run gen.go; DO NOT EDIT

package publicsuffix

const version = "subset of publicsuffix.org's effective_tld_names.dat, hg revision 05b11a8d1ace (2012-11-09)"

const (
	nodeTypeNormal     = 0
	nodeTypeException  = 1
	nodeTypeParentOnly = 2
)

// numTLD is the number of top level domains.
const numTLD = 6

// Text is the combined text of all labels.
const text = "british-libraryawatarparliamentfukuchiyamashinacionakagyoyamazak" +
	"itayabe164gvin-addretinagaokakyotambainelip6irisakyotanabejetjoy" +
	"ojpblogspotkizujitawarakumiyamakyotangobiernoelectronicomecongre" +
	"sodelalengua3kyotominamiyamashiromiyazurideducitymukobepromocion" +
	"antanational-library-scotlandseikameokamodurnlschigashiyamaizuru" +
	"bazwazuka"

// Nodes is the list of nodes. Each node is encoded as two uint32 values.
//
// The first uint32 encodes the node's children, nodeType, and a wildcard bit.
// In the //-comment after each node's data, the indexes of the children are
// formatted as (0x1234-0x1256). The nodeType is printed as + for normal, ! for
// exception, and o for parent-only nodes that have children but don't match a
// domain in their own right. The * denotes the wildcard bit. The layout within
// the uint32, from MSB to LSB, is:
//	[2] nodeType [1] wildcard [13] number of children [16] first child.
// If a node has no children then the low 29 bits are zero.
//
// The second uint32 encodes the node's text. The layout is:
//	[24] text offset [8] text length.
//
// TODO(nigeltao): this table has a lot of zeroes, for childless nodes. It
// would be tight, but it should be possible to use only 32 bits per node
// instead of 64, with an offset into a parent-child table. A back-of-the-
// envelope calculation suggests that at 6000 rows (of which 90% are leaves),
// this could save an extra 20KiB of data.
var nodes = [...][2]uint32{
	{0x00060006, 0x00005902}, // 0x0000 (0x0006-0x000c) +  ao
	{0xa00a000c, 0x00000c02}, // 0x0001 (0x000c-0x0016) o* ar
	{0x80060017, 0x00001304}, // 0x0002 (0x0017-0x001d) o  arpa
	{0x0002001d, 0x00008102}, // 0x0003 (0x001d-0x001f) +  jp
	{0xa00b003f, 0x00002002}, // 0x0004 (0x003f-0x004a) o* uk
	{0xa0000000, 0x00014202}, // 0x0005 (-------------) o* zw
	{0x00000000, 0x0000b602}, // 0x0006 (-------------) +  co
	{0x00000000, 0x0000ea02}, // 0x0007 (-------------) +  ed
	{0x00000000, 0x00004a02}, // 0x0008 (-------------) +  gv
	{0x00000000, 0x00000202}, // 0x0009 (-------------) +  it
	{0x00000000, 0x00008502}, // 0x000a (-------------) +  og
	{0x00000000, 0x00008202}, // 0x000b (-------------) +  pb
	{0x80010016, 0x0000b603}, // 0x000c (0x0016-0x0017) o  com
	{0x40000000, 0x0000ba13}, // 0x000d (-------------) !  congresodelalengua3
	{0x40000000, 0x0000ea04}, // 0x000e (-------------) !  educ
	{0x40000000, 0x0000a513}, // 0x000f (-------------) !  gobiernoelectronico
	{0x40000000, 0x0000b805}, // 0x0010 (-------------) !  mecon
	{0x40000000, 0x00002d06}, // 0x0011 (-------------) !  nacion
	{0x40000000, 0x0000b403}, // 0x0012 (-------------) !  nic
	{0x40000000, 0x0000f709}, // 0x0013 (-------------) !  promocion
	{0x40000000, 0x00005206}, // 0x0014 (-------------) !  retina
	{0x40000000, 0x00013f03}, // 0x0015 (-------------) !  uba
	{0x00000000, 0x00008308}, // 0x0016 (-------------) +  blogspot
	{0x00000000, 0x00004604}, // 0x0017 (-------------) +  e164
	{0x00000000, 0x00004c07}, // 0x0018 (-------------) +  in-addr
	{0x00000000, 0x00006903}, // 0x0019 (-------------) +  ip6
	{0x00000000, 0x00006c04}, // 0x001a (-------------) +  iris
	{0x00000000, 0x0000e603}, // 0x001b (-------------) +  uri
	{0x00000000, 0x00012a03}, // 0x001c (-------------) +  urn
	{0xa001001f, 0x0000f304}, // 0x001d (0x001f-0x0020) o* kobe
	{0x001f0020, 0x0000cd05}, // 0x001e (0x0020-0x003f) +  kyoto
	{0x40000000, 0x0000ed04}, // 0x001f (-------------) !  city
	{0x00000000, 0x00004205}, // 0x0020 (-------------) +  ayabe
	{0x00000000, 0x00001f0b}, // 0x0021 (-------------) +  fukuchiyama
	{0x00000000, 0x0001300b}, // 0x0022 (-------------) +  higashiyama
	{0x00000000, 0x0000e803}, // 0x0023 (-------------) +  ide
	{0x00000000, 0x00006503}, // 0x0024 (-------------) +  ine
	{0x00000000, 0x00007d04}, // 0x0025 (-------------) +  joyo
	{0x00000000, 0x00012007}, // 0x0026 (-------------) +  kameoka
	{0x00000000, 0x00012504}, // 0x0027 (-------------) +  kamo
	{0x00000000, 0x00003f04}, // 0x0028 (-------------) +  kita
	{0x00000000, 0x00008b04}, // 0x0029 (-------------) +  kizu
	{0x00000000, 0x00009708}, // 0x002a (-------------) +  kumiyama
	{0x00000000, 0x00005d08}, // 0x002b (-------------) +  kyotamba
	{0x00000000, 0x00007109}, // 0x002c (-------------) +  kyotanabe
	{0x00000000, 0x00009f08}, // 0x002d (-------------) +  kyotango
	{0x00000000, 0x00013907}, // 0x002e (-------------) +  maizuru
	{0x00000000, 0x0000d206}, // 0x002f (-------------) +  minami
	{0x00000000, 0x0000d20f}, // 0x0030 (-------------) +  minamiyamashiro
	{0x00000000, 0x0000e106}, // 0x0031 (-------------) +  miyazu
	{0x00000000, 0x0000f104}, // 0x0032 (-------------) +  muko
	{0x00000000, 0x0000560a}, // 0x0033 (-------------) +  nagaokakyo
	{0x00000000, 0x00003207}, // 0x0034 (-------------) +  nakagyo
	{0x00000000, 0x0000ff06}, // 0x0035 (-------------) +  nantan
	{0x00000000, 0x00003809}, // 0x0036 (-------------) +  oyamazaki
	{0x00000000, 0x00006f05}, // 0x0037 (-------------) +  sakyo
	{0x00000000, 0x00011d05}, // 0x0038 (-------------) +  seika
	{0x00000000, 0x00007406}, // 0x0039 (-------------) +  tanabe
	{0x00000000, 0x00008e03}, // 0x003a (-------------) +  uji
	{0x00000000, 0x00008e09}, // 0x003b (-------------) +  ujitawara
	{0x00000000, 0x00014306}, // 0x003c (-------------) +  wazuka
	{0x00000000, 0x00002609}, // 0x003d (-------------) +  yamashina
	{0x00000000, 0x00000e06}, // 0x003e (-------------) +  yawata
	{0x40000000, 0x00008302}, // 0x003f (-------------) !  bl
	{0x40000000, 0x0000000f}, // 0x0040 (-------------) !  british-library
	{0x8001004a, 0x0000b602}, // 0x0041 (0x004a-0x004b) o  co
	{0x40000000, 0x00007a03}, // 0x0042 (-------------) !  jet
	{0x40000000, 0x00012703}, // 0x0043 (-------------) !  mod
	{0x40000000, 0x00010419}, // 0x0044 (-------------) !  national-library-scotland
	{0x40000000, 0x00006603}, // 0x0045 (-------------) !  nel
	{0x40000000, 0x0000b403}, // 0x0046 (-------------) !  nic
	{0x40000000, 0x00012c03}, // 0x0047 (-------------) !  nls
	{0x40000000, 0x0000150a}, // 0x0048 (-------------) !  parliament
	{0xa0000000, 0x00012e03}, // 0x0049 (-------------) o* sch
	{0x00000000, 0x00008308}, // 0x004a (-------------) +  blogspot
}
