// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs_darwin.go

package route

const (
	sizeofIfMsghdr2Darwin15 = 0xa0
	sizeofIfData64Darwin15  = 0x80

	sizeofRtMsghdr2Darwin15 = 0x5c
)
