// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs_freebsd.go

package route

const (
	sizeofRtMsghdrFreeBSD10  = 0x5c
	sizeofRtMetricsFreeBSD10 = 0x38

	sizeofIfMsghdrFreeBSD7  = 0x70
	sizeofIfMsghdrFreeBSD8  = 0x70
	sizeofIfMsghdrFreeBSD9  = 0x70
	sizeofIfMsghdrFreeBSD10 = 0x70
	sizeofIfMsghdrFreeBSD11 = 0xa8

	sizeofRtMsghdrFreeBSD10Emu  = 0x5c
	sizeofRtMetricsFreeBSD10Emu = 0x38

	sizeofIfMsghdrFreeBSD7Emu  = 0x70
	sizeofIfMsghdrFreeBSD8Emu  = 0x70
	sizeofIfMsghdrFreeBSD9Emu  = 0x70
	sizeofIfMsghdrFreeBSD10Emu = 0x70
	sizeofIfMsghdrFreeBSD11Emu = 0xa8
)
